version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ftube

    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql



